_commit: v0.1.0-13-ga6cd339
_src_path: git@github.com:benwebber/open-data-toronto-copier.git
name: Public Notices
project: open-data-toronto-public-notices
repo: benwebber/open-data-toronto-public-notices
slug: public_notices
url: https://open.toronto.ca/dataset/public-notices/
